apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/my-repo/my-app.git'
    targetRevision: main
    path: iac/test-app/cd/overlays/prod
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: jonny-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true