apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jonny-dev
nameSuffix: -dev
labels:
  - pairs:
      app.kubernetes.io/name: test-app-dev
    includeSelectors: true
resources:
  - ../../base